:concurrency: 1
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
staging:
  :concurrency: 2
production:
  :concurrency: 10
:queues:
  - default

tasks: &tasks
  PopulateJob:
    cron: '0 12 * * * *'
    queue: default
    description: "Populate from yesterday's articles"

schedule:
  <<: *tasks
